plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/joabnicholson/Documents/websites-app/react-arka/server/dist/client"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/joabnicholson/Documents/websites-app/react-arka/server"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]